services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend